title: My theme
logo: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjpRv2uG3MkvqIg7cMn2LORMM8F3ZhCHUGVoONG5pd9ONy51_ClH5IxlA&s
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
